language: go
env:
  global:
    - GO111MODULE=on

matrix:
  include:
    - go: 1.11.x
      env: DEPLOY_BUILD=true
    - go: tip

install:
  - GO111MODULE=off go get -u golang.org/x/tools/cmd/goimports
  - go mod download

script:
  - diff <(goimports -d *.go cmd/gocloc/main.go examples/*) <(printf "")
  - go test -v ./
